### ISSUE TITLE
Is it possible to "thread" on two mailboxes at once?

### ISSUE THREAD

**Issue by s77rt** [emersion/go-imap-sortthread#7]
Hi,
First thanks of your work on the go-imap* :)

I'm wondering if it's possible to thread on two mailboxes at once? mainly INBOX and SENT, to get a conversation like (same as gmail does)

or any suggested approach ?

**Comment by foxcpp** [comment]
THREAD command does not allow to specify multiple mailboxes. You can send multiple commands for each mailbox and merge them. Sadly, this kinda defeats the point since you will need to have some merging algorithm operating on message contents and not letting server do everything.

I would try the following:
1. Run THREAD on INBOX.
2. Fetch Subject all root threads.
4. Run THREAD on Sent with search criteria matching base subject and merge results into response from step 1. 

Depending on what exactly you want, that might be enough.

**Comment by s77rt** [comment]
@foxcpp 
it seems kinda overkill, :/

do you have a working code for that?

**Comment by foxcpp** [comment]
No. Results of ORDEREDSUBJECT threading algorithm should be trivial to merge. The tricky part is to match threads in Sent and INBOX.

Run THREAD ORDEREDSUBJECT INBOX for whatever subset of messages you need.
Take first message from each thread. Get Subject header field, strip Re:/Fwd: (note: can have multiple of these and they can be mixed), Do THREAD with Subject search criteria using "base subject" obtained. Concat ID lists and sort them. Repeat for each thread and cache it somewhere to not be so slow next time.

**Comment by emersion** [comment]
Yeah, unfortunately IMAP operations can only operate on a single mailbox as @foxcpp said.
